// src/redux/constants/action-types.js

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const HANDLE_SIGNUP = "HANDLE_SIGNUP";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";
export const HANDLE_ERROR = "HANDLE_ERROR";
export const HANDLE_GET_RESTAURANT_LOCATIONS = "HANDLE_GET_RESTAURANT_LOCATIONS";
export const HANDLE_ADD_RESTAURANT = "HANDLE_ADD_RESTAURANT";
export const HANDLE_ADD_LOCATION = "HANDLE_ADD_LOCATION";
export const HANDLE_GET_ITEMS = "HANDLE_GET_ITEMS";
